[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin  = "*"
    Access-Control-Allow-Methods = "GET, POST, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from   = "/api/*"
  to     = "https://lead-collector-nl89.onrender.com/api/:splat"
  status = 200
  force  = true
